# Generated by Django 3.1 on 2025-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250806_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default='color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
