# Generated by Django 3.1 on 2025-07-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20250728_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slud',
            new_name='slug',
        ),
    ]
